## NiaPy features

### How to run build-in algorithm?

In [3]:
from NiaPy.algorithms.basic import GreyWolfOptimizer
from NiaPy.task import StoppingTask

for i in range(10):
    task = StoppingTask(D=10, nFES=1000, benchmark='pinter')
    algorithm = GreyWolfOptimizer(NP=20)
    best = algorithm.run(task)
    print(best[-1])

0.7813053929661877
74.09803267615628
10.83236490700716
0.08334023085719769
4.807318522528462
0.06473222791990513
57.21435646093426
10.26971948544406
55.93110799296939
0.27322931095775854


### How to create own benchmark?

In [4]:
from NiaPy.task import StoppingTask, OptimizationType
from NiaPy.benchmarks import Benchmark
from NiaPy.algorithms.basic import ParticleSwarmAlgorithm

# our custom benchmark class
class MyBenchmark(Benchmark):
    def __init__(self):
        Benchmark.__init__(self, -10, 10)

    def function(self):
        def evaluate(D, sol):
            val = 0.0
            for i in range(D): val += sol[i] ** 2
            return val
        return evaluate

In [5]:
for i in range(10):
    task = StoppingTask(D=20, nGEN=100, optType=OptimizationType.MINIMIZATION, benchmark=MyBenchmark())

    # parameter is population size
    algo = GreyWolfOptimizer(NP=20)

    # running algorithm returns best found minimum
    best = algo.run(task)

    # printing best minimum
    print(best[-1])

4.815324346340003e-08
3.351723802547693e-09
3.089398063981768e-08
1.0804130356567129e-08
7.389819843220287e-09
1.390865554115852e-08
7.808594227849607e-09
1.55795958130749e-08
8.679462573922133e-09
1.3275057901741627e-08


### Runner feature

In [8]:
import NiaPy

algorithms = [
    'ArtificialBeeColonyAlgorithm',
    'GreyWolfOptimizer'
]
benchmarks = ['ackley', 'whitley', 'alpine2', MyBenchmark()]

NiaPy.Runner(10, 10000, 3, algorithms, benchmarks).run(export='json', verbose=True)
"""
Attributes:
    D (int): Dimension of problem
    nFES (int): Number of function evaluations
    nRuns (int): Number of repetitions
    useAlgorithms (List[Algorithm]): List of algorithms to run
    useBenchmarks (List[Benchmarks]): List of benchmarks to run
"""

INFO:NiaPy.runner.Runner:Running ArtificialBeeColonyAlgorithm...
INFO:NiaPy.runner.Runner:Running ArtificialBeeColonyAlgorithm algorithm on ackley benchmark...
INFO:NiaPy.runner.Runner:Running ArtificialBeeColonyAlgorithm algorithm on whitley benchmark...
INFO:NiaPy.runner.Runner:Running ArtificialBeeColonyAlgorithm algorithm on alpine2 benchmark...
INFO:NiaPy.runner.Runner:Running ArtificialBeeColonyAlgorithm algorithm on MyBenchmark benchmark...
INFO:NiaPy.runner.Runner:---------------------------------------------------
INFO:NiaPy.runner.Runner:Running GreyWolfOptimizer...
INFO:NiaPy.runner.Runner:Running GreyWolfOptimizer algorithm on ackley benchmark...
INFO:NiaPy.runner.Runner:Running GreyWolfOptimizer algorithm on whitley benchmark...
INFO:NiaPy.runner.Runner:Running GreyWolfOptimizer algorithm on alpine2 benchmark...
INFO:NiaPy.runner.Runner:Running GreyWolfOptimizer algorithm on MyBenchmark benchmark...
INFO:NiaPy.runner.Runner:-------------------------------------------------

'\nAttributes:\n    D (int): Dimension of problem\n    nFES (int): Number of function evaluations\n    nRuns (int): Number of repetitions\n    useAlgorithms (List[Algorithm]): List of algorithms to run\n    useBenchmarks (List[Benchmarks]): List of benchmarks to run\n'

In [9]:
!ls export

2020-10-17 16.13.39.620134.json 2020-10-17 16.55.38.929005.json


In [12]:
import json

In [13]:
def load_json_file(path: str) -> dict:
    with open(path) as f:
        return json.load(f)

In [14]:
log_content = load_json_file("./export/2020-10-17 16.55.38.929005.json")

In [15]:
log_content

{'ArtificialBeeColonyAlgorithm': {'ackley': [[[0.0,
     0.0,
     0.0,
     -0.0,
     0.0,
     -0.0,
     0.0,
     0.0,
     -0.0,
     -0.0],
    0.0],
   [[-2.317e-07,
     -5.8989e-06,
     -0.0002018338,
     4.56e-08,
     -9.1737e-06,
     -2.347e-07,
     6.999e-07,
     6.0823e-06,
     -3.7e-09,
     -1.3141e-06],
    0.000256015],
   [[0.0, 0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, 0.0, 0.0], 0.0]],
  'whitley': [[[1.3982014827,
     1.3971356479,
     1.284139109,
     1.3962348678,
     1.3989101902,
     1.4514134129,
     1.3978095884,
     1.3977227607,
     1.3979636613,
     1.3969067726],
    40.8851392178],
   [[0.9869983119,
     0.9802401824,
     0.968491615,
     0.9840129748,
     0.9870348414,
     0.6999417535,
     0.9618919842,
     0.8711280773,
     1.1885955403,
     1.0363015377],
    41.0211899819],
   [[1.0571950637,
     1.0547493152,
     1.0519578954,
     1.0601311355,
     1.0571095174,
     1.0573256435,
     1.0592379642,
     1.1479388307,
   

### Implemented algorithms

* **BatAlgorithm** (Yang, Xin-She. “A new metaheuristic bat-inspired algorithm.” Nature inspired cooperative strategies for optimization (NICSO 2010). Springer, Berlin, Heidelberg, 2010. 65-74.)
* **FireflyAlgorithm** (Fister, I., Fister Jr, I., Yang, X. S., & Brest, J. (2013). A comprehensive review of firefly algorithms. Swarm and Evolutionary Computation, 13, 34-46.)
* **DifferentialEvolutionAlgorithm** (Storn, Rainer, and Kenneth Price. “Differential evolution - a simple and efficient heuristic for global optimization over continuous spaces.” Journal of global optimization 11.4 (1997): 341-359.)
* **FlowerPollinationAlgorithm** (Yang, Xin-She. “Flower pollination algorithm for global optimization. International conference on unconventional computing and natural computation. Springer, Berlin, Heidelberg, 2012)
* **GreyWolfOptimizer** (Mirjalili, Seyedali, Seyed Mohammad Mirjalili, and Andrew Lewis. “Grey wolf optimizer.” Advances in engineering software 69 (2014): 46-61.)
* **ArtificialBeeColonyAlgorithm** (Karaboga, D., and Bahriye B. “A powerful and efficient algorithm for numerical function optimization: artificial bee colony (ABC) algorithm.” Journal of global optimization 39.3 (2007): 459-471.)
* **ParticleSwarmAlgorithm** (Kennedy, J. and Eberhart, R. “Particle Swarm Optimization”. Proceedings of IEEE International Conference on Neural Networks. IV. pp. 1942–1948, 1995.)
* **BareBonesFireworksAlgorithm** (Junzhi Li, Ying Tan, The bare bones fireworks algorithm: A minimalist global optimizer, Applied Soft Computing, Volume 62, 2018, Pages 454-462, ISSN 1568-4946)

And much, much more...


### How to implement your own algorithm?

```python

class Algorithm:

	@staticmethod
	def typeParameters():
		pass

	@staticmethod
	def algorithmInfo():
		pass

	def setParameters(self, NP=50, InitPopFunc=defaultNumPyInit, itype=None, **kwargs):
		pass

	def getParameters(self):
		pass

	def rand(self, D=1):
		pass

	def uniform(self, Lower, Upper, D=None):
		pass

	def normal(self, loc, scale, D=None):
		pass
    
	def randn(self, D=None):
		pass

	def randint(self, Nmax, D=1, Nmin=0, skip=None):
		pass

	def getBest(self, X, X_f, xb=None, xb_f=inf):
		pass

	def initPopulation(self, task):
		pass

	def runIteration(self, task, pop, fpop, xb, fxb, **dparams):
		pass

	def runYield(self, task):
		pass
    
	def runTask(self, task):
		pass

	def run(self, task):
		pass
```

In [16]:
import logging

from numpy import full

from NiaPy.algorithms.algorithm import Algorithm

logging.basicConfig()
logger = logging.getLogger()
logger.setLevel('INFO')


class ReimplementationOfBatAlgorithm(Algorithm):
    r"""
    Implementation of Bat algorithm.
    Authors:
    Iztok Fister Jr., Marko Burjek and Klemen Berkovič
    License:
    MIT
    """

    @staticmethod
    def typeParameters():
        d = Algorithm.typeParameters()
        d.update({
            'A': lambda x: isinstance(x, (float, int)) and x > 0,
            'r': lambda x: isinstance(x, (float, int)) and x > 0,
            'Qmin': lambda x: isinstance(x, (float, int)),
            'Qmax': lambda x: isinstance(x, (float, int))
        })
        return d

    def setParameters(self, NP=40, A=0.5, r=0.5, Qmin=0.0, Qmax=2.0, **ukwargs):
        Algorithm.setParameters(self, NP=NP, **ukwargs)
        self.A, self.r, self.Qmin, self.Qmax = A, r, Qmin, Qmax

    def getParameters(self):
        d = Algorithm.getParameters(self)
        d.update({
            'A': self.A,
            'r': self.r,
            'Qmin': self.Qmin,
            'Qmax': self.Qmax
        })
        return d

    def initPopulation(self, task):
        Sol, Fitness, d = Algorithm.initPopulation(self, task)
        S, Q, v = full([self.NP, task.D], 0.0), full(self.NP, 0.0), full([self.NP, task.D], 0.0)
        d.update({'S': S, 'Q': Q, 'v': v})
        return Sol, Fitness, d

    def localSearch(self, best, task, **kwargs):
        return task.repair(best + 0.001 * self.normal(0, 1, task.D))

    def runIteration(self, task, Sol, Fitness, xb, fxb, S, Q, v, **dparams):
        for i in range(self.NP):
            Q[i] = self.Qmin + (self.Qmax - self.Qmin) * self.uniform(0, 1)
            v[i] += (Sol[i] - xb) * Q[i]
            if self.rand() > self.r: S[i] = self.localSearch(best=xb, task=task, i=i, Sol=Sol)
            else: S[i] = task.repair(Sol[i] + v[i], rnd=self.Rand)
            Fnew = task.eval(S[i])
            if (Fnew <= Fitness[i]) and (self.rand() < self.A): Sol[i], Fitness[i] = S[i], Fnew
            if Fnew <= fxb: xb, fxb = S[i].copy(), Fnew
        return Sol, Fitness, xb, fxb, {'S': S, 'Q': Q, 'v': v}

In [17]:
NiaPy.Runner(10, 10000, 3, [ReimplementationOfBatAlgorithm()], benchmarks).run(export='json', verbose=True)

INFO:NiaPy.runner.Runner:Running ReimplementationOfBatAlgorithm...
INFO:NiaPy.runner.Runner:Running ReimplementationOfBatAlgorithm algorithm on ackley benchmark...
INFO:NiaPy.runner.Runner:Running ReimplementationOfBatAlgorithm algorithm on whitley benchmark...
INFO:NiaPy.runner.Runner:Running ReimplementationOfBatAlgorithm algorithm on alpine2 benchmark...
INFO:NiaPy.runner.Runner:Running ReimplementationOfBatAlgorithm algorithm on MyBenchmark benchmark...
INFO:NiaPy.runner.Runner:---------------------------------------------------
INFO:NiaPy.runner.Runner:Export to JSON file completed!


{'ReimplementationOfBatAlgorithm': {'ackley': [(array([ 16.99396566,   9.99616302,  16.99347429,   6.99741299,
            -5.9975966 ,   1.99884474,  -3.99824338,   1.99958051,
           -14.99422152, -11.99483785]),
    17.670124807501907),
   (array([ 2.9967827 , -2.99684072,  8.99113365, -5.9939184 ,  0.9989893 ,
            4.99523905,  9.99060081, -9.98917653, 15.98375022,  0.99852204]),
    15.84527599723112),
   (array([-16.99020248,   4.99710569,  -0.9996475 ,   1.99840988,
            -4.99698753,  -1.99855434,  -3.99745066,  -7.99503179,
            -7.99523944, -19.9887936 ]),
    16.973581490181775)],
  'whitley': [(array([-0.90415136,  2.31772047, -0.65189363,  0.81069839, -4.08515599,
           -2.09973738, -4.50267434,  3.94277098,  3.8479795 ,  2.95765516]),
    10391632.649188073),
   (array([ 3.54758344, -2.71028105, -1.62677101, -2.00348373,  1.10730132,
           -2.70557423, -3.54574052,  3.46990655, -2.47266566, -3.01374772]),
    3753086.327384895),
   (array

## Community:

https://github.com/NiaOrg/NiaPy/graphs/contributors?from=2018-02-04&to=2020-10-17&type=c